package com.project.principal.models;

import jakarta.persistence.*;
import lombok.Data;
/**
 * This class represents a medical history record in the system.
 * @author lopezs.dev
 */
@Data
@Entity
@Table(name = "Historial_Medico")
public class HistorialMedicoModel {

    /**
     * Unique identifier for the medical history record. This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Identifier of the patient associated with this medical history record.
     */
    @Column(name = "pacienteId")
    private String pacienteId;

    /**
     * Identifier of the doctor associated with this medical history record.
     */
    @Column(name = "medicoId")
    private String medicoId;

    /**
     * Diagnosis for the patient's condition.
     */
    @Column(name = "diagnostico")
    private String diagnostico;

    /**
     * Treatment plan prescribed for the patient.
     */
    @Column(name = "tratamiento")
    private String tratamiento;
}
